on:
  push:
    tags:
      - '*'
jobs:
  publish-version:
    name: Publish the current release version
    uses: e-CODEX/workflows/.github/workflows/maven-release-publish.yaml@main
    with:
      java-version: 21
      maven-repo-id: 'releases'
