on:
  push:
    branches:
      - develop
jobs:
  publish:
    uses: e-CODEX/workflows/.github/workflows/maven-publish-snapshot.yaml@main
    with:
      java-version: 21
      maven-repo-id: 'snapshots'
